package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Sunday, April 28, 2024 12:29:13 PM IST
*/


// Define an interface named Reverse
public interface ReverseOperations 
{

  // Declare a method named reverse_string that takes a string as input and returns a string
  String reverse_string (String str);
} // interface ReverseOperations
